### PR TITLE
Kanban Capstone: Add windows popup

### PR DESCRIPTION
**Pull request by Emmy-github-webdev**
# Kanban Capstone: Add windows popup

In this project, I 
- Add windows pop up that displays the details of the meal item selected
- Add comment post markup
- Add list comment markup

### CODE REVIEW

**Review by lu-jim — CHANGES_REQUESTED** [review]
Hello! @Emmy-github-webdev 

We need to review this PR to be able to move forward. 
## 🔴 Required changes 🔴 
- According to issues #15 #6 and #3, it is my responsibility to load the list of items, retrieve them from the API, and count them on the home title. Your changes override my features either changing them completely or rendering them useless(see my last commit with all of my tasks done vs your version.
  - Your version
image

  - My working implementation
  image

- According to the Collaboration policy in the [Microverse Student Handbook](https://www.notion.so/microverse/Collaboration-policy-1dd1dc06ca774628aa99d0e3d9dd6d55):

> You should never make changes to another students' code, just like in the workplace you will not make changes to your colleagues' work without their consent.

Per the recommendations on the same document, please revert the changes done to my features(as they are required for the already in review PR #26) and refactor the current implementation. As we had discussed in the past few calls, I'm available to make changes on the buttons in place to accommodate for the popup, as I had already done on PR #26

**Comment by Emmy-github-webdev** [comment]
@lu-jim,

Thank you for a great job. 👍 

Your initial design is great and it will be my pleasure to use it exactly. Can we connect and fix the pop-up issue I was having with the design? 

The changes done are to make the pop-up work. This does not merge to the default branch to render your work useless. 

I appreciate you as my coding partner.  I cannot render your code useless.

I told you on a call that for the popup to work, I need to make some changes.

The styling changed because of the limitation to control the bootstrap.

**Comment by lu-jim** [comment]
Emmanuel,

Your current PR still changes the working implementation I had, commenting out my code and replacing it with your own. You should have no need to change my code if you want to generate a popup after clicking a button. In your previous reply, you say this. Let me go through my issues one by one

> @lu-jim,
> 
> Thank you for a great job. +1
> 
> Your initial design is great and it will be my pleasure to use it exactly. Can we connect and fix the pop-up issue I was having with the design?
> 
1.-  If your implementation is having issues generating a popup when clicking a button, it is up to your code. As stated in the code of conduct, you should never make changes to another students' code, just like in the workplace you will not make changes to your colleagues' work without their consent.

I offered my help several times and even created the function `Meals.getRecipe()` that will output each meal data in a string, which would only need to be parsed using the object properties (such as `idMeal`, `strInstructions`, etc). No need to replace my implementation on your own is required. If you need to change how the button is working, feel free to let me know, as I have offered my help several times to make generating the popup easier for you.

> The changes done are to make the pop-up work. This does not merge to the default branch to render your work useless.
> 
2. When merging into dev, this will replace my implementation and thus render my work useless. As stated on the Microverse specifications, each partner has its own set of responsibilities. Considering my solution for issues #3 #6 #9 and #12 are operational and either has been approved by you or hasn't got any feedback, there is no reason to replace them with yours. 
> I appreciate you as my coding partner. I cannot render your code useless.
> 
> I told you on a call that for the popup to work, I need to make some changes.
> 
3. And in that call I asked you why would you need to change my implementation to create a modal when clicking a button. I'm still waiting for this reason.
> The styling changed because of the limitation to control the bootstrap.
4. As you can see in the working version already in place in PR #26, my styling with bootstrap had no such limitations. If you don't want to use bootstrap for your features is completely fine, but it would be up to you to implement the corresponding CSS. I don't see how bootstrap would require you to change the font from IBM Mono to Poppins, for example. Let me know if I'm overlooking anything.

**Review by lu-jim — APPROVED** [review]
@Emmy-github-webdev 

Your feature is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Comment by Emmy-github-webdev** [comment]
Thank you @lu-jim

**Pull request merged**
